dataset: &dataset binary_cifar100
data_root: ./datasets
total_cls_num: &total_cls_num 100
init_cls_num: &init_cls_num 10
inc_cls_num: &inc_cls_num 10
task_num: 10
image_size: 32
save_path: ./

train_trfms:
  - RandomCrop:
      size: 32
      padding: 4
  - RandomHorizontalFlip: {}
  - ToTensor: {}
  - Normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]
test_trfms:
  - ToTensor: {}
  - Normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [0.2675, 0.2565, 0.2761]

seed: 0
deterministic: True
device_ids: auto
n_gpu: 1
num_workers: 4
pin_memory: False

batch_size: 32
init_epoch: 50
epoch: 50
val_per_epoch: 50
testing_times: 1
testing_per_task: True
setting: task-agnostic
eval_with_test: True

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [35, 45]

backbone:
  name: resnet18
  kwargs:
    num_classes: *total_cls_num
    args:
      dataset: *dataset

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 32
    strategy: random

classifier:
  name: PaperER
  kwargs:
    num_class: *total_cls_num
    feat_dim: 512
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    minibatch_size: 32
    buffer_storage: tensor
