includes:
  - zz_EWCDR/tinyimagenet_common.yaml

init_cls_num: 40
inc_cls_num: 40
task_num: 5

backbone:
  name: resnet18
  kwargs:
    num_classes: 200
    args:
      dataset: tiny-imagenet
      init_cls_num: 40
      inc_cls_num: 40

classifier:
  name: EWCDR
  kwargs:
    num_class: 200
    feat_dim: 512
    init_cls_num: 40
    inc_cls_num: 40
    task_num: 5
    lamda: 10000
    omega_max: 0.0001

