name: Sync to Hugging Face

on:
  push:
    branches:
      - main


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Upload to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |

        pip install huggingface_hub

        hf upload \
        RL-MIND/LibContinual \
        . \
        --repo-type model \
        --commit-message "Sync from GitHub"
